name: Sonar Project Generator
description: >
  Generate or Configure a SonarQuebe or SonarCloud project
inputs:
  platform:
    description: "Sonar Platform"
    default: "sonarcloud"
  organization:
    description: "Sonar Organization"
    default: "${{ github.repository_owner }}"
  visibility:
    description: Whether the created project should be visible to everyone, or only specific user/groups.
    default: "private"
  project:
    description: Key of the project
    default: "${{ github.event.repository.name }}"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    [
      "--platform", "${{ inputs.platform }}",
      "--organization", "${{ inputs.organization }}",
      "--visibility", "${{ inputs.visibility }}",
      "--project", "${{ inputs.project }}",
    ]