name: Sonar Project Generator
description: >
  Generate or Configure a SonarQuebe or SonarCloud project
inputs:
  platform:
    description: "Sonar Platform"
    default: "sonarcloud"
  organization:
    description: "Sonar Organization"
    default: "${{ github.repository_owner }}"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    [
      "--platform", "${{ inputs.platform }}",
      "--organization", "${{ inputs.organization }}",
    ]