name: 'Sonar Project'
description: 'Greet someone and record the time'
inputs:
  platform:
    description: 'Sonar Platform'
    default: 'sonarcloud'
  organization:
    description: 'Sonar Organization'
    default: '${{ github.repository_owner }}'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: [
    "--platform", "${{ inputs.platform }}",
    "--organization", "${{ inputs.organization }}",
  ]
